#!/usr/bin/ruby

require 'optparse'

########## parsing inputs
optparse = OptionParser.new do|opts|
  opts.on('-n', '--net NETWORK-NAME', 'Specify name of the network.') do |n|
    options[:net] = n
    options[:key] = NIL
  end
  opts.on('-k', '--key NETWORK-KEY', 'Specify network key.') {|options[:key]|}
  opts.on('-l', '--list', 'List available networks') {|options[:list]|}
end
optparse.parse!
##########

`ifconfig wlan0 down`
`ifconfig wlan0 up`

if options[:list] or not options[:net]
  puts "Listing..."
  puts "----------"
  puts `iwlist wlan0 scanning`.scan(/ESSID:"(.*?)"/)
else
  puts "connecting..."
  cmd = "iwconfig wlan0 essid #{options[:net]}"
  if options[:key] 
    cmd = cmd + " key #{options[:key]}"
  end
  `#{cmd}`
  puts "dhcp attempt..."

  begin
    timeout(5) do
      `dhclient wlan0`
    end
  rescue Exception => e
    puts "second dhcp attempt..."
    exec "dhclient wlan0"
  end
end
