#!/usr/bin/ruby

require 'optparse'

########## parsing inputs
options={:net => "[default-network]", :key => "[default-key]"}
optparse = OptionParser.new do|opts|
  opts.on('-n', '--net NETWORK-NAME', 'Specify name of the network.') do |n|
    options[:net] = n
    options[:key] = NIL
  end
  opts.on('-k', '--key NETWORK-KEY', 'Specify network key.') do |k|
    options[:key] = k
  end
end
optparse.parse!
##########

cmd = "iwconfig wlan0 essid #{options[:net]}"
if options[:key]
  cmd = cmd + " key #{options[:key]}"
end

`ifconfig wlan0 down`
`ifconfig wlan0 up`
`#{cmd}`
exec "dhclient wlan0"
