#! /usr/bin/ruby

ARGV.each do |target|
  file_ext = target.scan(/\.\w*$/)[0]
  name = target.sub(file_ext, "")
  unless file_ext==".avi"
    puts "Converting to intermediate filetype..."
    `mencoder "#{target}" -ovc lavc -oac lavc -ffourcc DX50 -o tmp.avi`
  end

  puts "Converting to mp3..."
  if file_ext ==".avi"
    `pacpl -t mp3 --outfile "#{name}" "#{target}"`
  else
    `pacpl -t mp3 --outfile "#{name}" tmp.avi`
    puts "Removing temp files..."
    `rm tmp.avi`
  end
end
