#!/usr/bin/ruby

require 'optparse'
require 'fileutils'

lang_options = Dir.entries(".").find_all{ |e| File.directory?(e) and not e =~ /^\./ }

options={:lang => "ruby", :force => false}
optparse = OptionParser.new do|opts|
  opts.on('-f', '--force', "Overwrite existing scripts in /usr/bin") do |v|
    options[:force] = v
  end
  opts.on('-l', '--lang LANGUAGE', 
          "Specify which scripts to install.",
          "Defaults to '#{options[:lang]}'. Supported languages: #{lang_options.join ", "}") do |l|
    options[:lang] = l
  end
end
optparse.parse!

if lang_options.member? options[:lang]
  scripts = Dir.entries(options[:lang]).find_all{ |e| not e =~ /^\./ }
  FileUtils.cd(options[:lang]) do
    Dir.entries(".").find_all{ |e| not e =~ /^\./ and not e =~ /~$/}.each do |file|
      if File.exists? "/usr/bin/#{file}" and not options[:force]
        puts "/usr/bin/#{file} exists, skipping"
      elsif File.exists? "/usr/bin/#{file}"
        File.delete "/usr/bin/#{file}"
        FileUtils.cp file, "/usr/bin/"
      else
        FileUtils.cp file, "/usr/bin/"
      end
    end
  end
else
  puts "Valid options are: #{lang_options.join ", "}"
end
