#!/usr/bin/ruby

require 'optparse'
require 'fileutils'

lang_options = Dir.entries(".").find_all{ |e| File.directory?(e) and not e =~ /^\./ }

options={:lang => "ruby", :force => false, :scripts => false}
optparse = OptionParser.new do|opts|
  opts.on('-f', '--force', "Overwrite existing scripts in /usr/bin") do |v|
    options[:force] = v
  end
  opts.on('-s', '--scripts a,b,c', Array, 
          "Specify which scripts to install (by default, all of them)") do |s|
    options[:scripts] = s
  end
  opts.on('-l', '--lang LANGUAGE', 
          "Specify which scripts to install.",
          "Defaults to '#{options[:lang]}'. Supported languages: #{lang_options.join ", "}") do |l|
    options[:lang] = l
  end
end
optparse.parse!

def get_scripts ()
  if options[:scripts]
    options[:scripts].each do |file|
      if not File.exists? file
        puts "#{file} is not supported in #{options[:lang]}"
      end
    end
    options[:scripts].find_all{ |s| File.exists?(e) and not e =~ /^\./}
  else
    Dir.entries(".").find_all{ |e| not e =~ /^\./ }
  end
end

if lang_options.member? options[:lang]
  FileUtils.cd(options[:lang]) do
    scripts = get_scripts()
    Dir.entries(".").find_all{ |e| not e =~ /^\./ and not e =~ /~$/}.each do |file|
      if File.exists? "/usr/bin/#{file}" and not options[:force]
        puts "/usr/bin/#{file} exists, skipping"
      else
        FileUtils.cp file, "/usr/bin/"
      end
    end
  end
else
  puts "Valid options are: #{lang_options.join ", "}"
end
