#!/usr/bin/ruby

require 'optparse'
require 'pp'
require 'fileutils'

archive_types = { 
  "tar"     => "tar -cvf",
  "tar.gz"  => "tar -zcvf",
  "tgz"     => "tar -zcvf",
  "tar.bz2" => "tar -jcvf",
  "zip"     => "zip" 
}

########## parsing inputs
options={:type => "tar"}
optparse = OptionParser.new do|opts|
  opts.on('-t', '--type FILE-TYPE', 
          'Specify archive type to make. Defaults to "tar". Supported types: #{archive_types.keys.join ", "})') do |t|
    options[:type] = t
  end
end
optparse.parse!
##########

ARGV.each do |target|
  if archive_types[options[:type]]
    `#{archive_types[options[:type]]} "#{target}.#{options[:type]}" "#{target}"`
  else
    puts "Supported types are #{archive_types.keys.join ", "}"
    exit
  end
end
