#!/usr/bin/ruby

require 'optparse'
require 'pp'
require 'fileutils'

commands = { "tar"     => "tar -cvf",
             "tar.gz"  => "tar -zcvf",
             "tar.bz2" => "tar -jcvf",
             "zip"     => "zip" }

########## parsing inputs
options={:type => "tar"}
optparse = OptionParser.new do|opts|
  opts.on('-t', '--type FILE-TYPE', 'Specify the archive type that you would like to generate (defaults to "tar"; supported types are "tar", "tar.gz", "tar.bz2" and "zip")') do |t|
    options[:type] = t
  end
end
optparse.parse!
##########

ARGV.each do |target|
  if commands[options[:type]]
    `#{commands[options[:type]]} #{target}.#{options[:type]} #{target}`
  else
    puts "Supported types are"
    commands.each{|k, v| puts "     #{k}"}
    exit
  end
end
