#!/usr/bin/python

import sys, os
from optparse import OptionParser

commands = { "tar"     : "tar -cvf",
             "tar.gz"  : "tar -zcvf",
             "tgz"     : "tar -zcvf",
             "tar.bz2" : "tar -jcvf",
             "zip"     : "zip" }

### parse command line options
parser = OptionParser()
parser.add_option("-t", "--type", dest="type", default="tar",
                  help = "Specify archive type to make. Defaults to 'tar'." + ", ".join(commands.keys()))
(options, args) = parser.parse_args()
##############################

try: cmd = commands[options.type] 
except KeyError as error:
    print "Supported types are: " + ", ".join(commands.keys())
    sys.exit()

for folder in args:
    os.system(cmd + " " + folder + "." + options.type + " " + folder)
