#!/usr/bin/python

import sys, os
from optparse import OptionParser

commands = { "tar"     : "tar -cvf",
             "tar.gz"  : "tar -zcvf",
             "tar.bz2" : "tar -jcvf",
             "zip"     : "zip" }

### parse command line options
parser = OptionParser()
parser.add_option("-t", "--type", dest="type", default="tar",
                  help="""Specify the archihve type you want to generate. Defaults to "tar".""")
(options, args) = parser.parse_args()
##############################

try: cmd = commands[options.type] 
except KeyError as error:
    print "Supported types are:"
    for k, v in commands.items():
        print "    " + k
    sys.exit()

for folder in args:
    os.system(cmd + " " + folder + "." + options.type + " " + folder)
