#!/usr/bin/ruby

commands = { "tar"     => "tar -xvf",
             "tar.gz"  => "tar -zxvf",
             "tar.bz2" => "tar -jxvf",
	     "unrar"   => "unrar",
             "zip"     => "unzip" }

ARGV.each do |target|
  file_type = target.match(/\.(.*?)$/)[1]
  if commands[file_type]
    `#{commands[file_type]} #{target}`
  else
    p "Dunno how to deal with '#{target.match(/\.(.*?)$/)[1]}' files"
  end
end
