#!/usr/bin/ruby

archive_types = { 
  "tar"     => "tar -xvf",
  "tar.gz"  => "tar -zxvf",
  "tgz"     => "tar -zxvf",
  "tar.bz2" => "tar -jxvf",
  "rar"     => "unrar",
  "zip"     => "unzip" 
}

ARGV.each do |target|
  file_type = target.match(/\.(\w*?)$/)[1]
  if archive_types[file_type]
    `#{archive_types[file_type]} #{target}`
  else
    puts "Dunno how to deal with '#{target.match(/\.(.*?)$/)[1]}' files"
  end
end
