#!/usr/bin/ruby

def wlan_connect(net_id, key)
  `ifconfig wlan0 down`
  `ifconfig wlan0 up`
  `iwconfig wlan0 essid #{net_id}#{key}`
  exec "dhclient wlan0"
end

if not ARGV[0]
  wlan_connect("[default-network]", " key [default-key]")
elsif ARGV.length==1
  wlan_connect(ARGV[0], NIL)
else
  wlan_connect(ARGV[0], " key #{ARGV[1]}")
end
