#! /usr/bin/python

import sys, os, re
from subprocess import call
from glob import glob

for target in sys.argv[1:]:
    name = re.search("^(.*?)\.\w*$", target).group(1)
    call(["mplayer", "-novideo", "-ao", 'pcm:file="tmp.wav"', target])
    call(["pacpl", "-v", "-t", "ogg", "--outfile", name, "tmp.wav"])
    os.remove("tmp.wav")
    for f in glob(name + "*wav"):
        os.remove(f)
