#!/usr/bin/python

import sys
from subprocess import call

for folder in sys.argv[1:]:
    clean = folder.rstrip("/")
    print "packing", clean
    call(["tar", "-zcvf", clean + ".tar.gz", clean, "--exclude=.git/*", "--exclude=*~"])
