#! /usr/bin/python3

import requests
import json
import os
from optparse import OptionParser

API_KEY = os.environ.get("ANTHROPIC_API_KEY")


def chat(model, messages, system=None):
    data = {"messages": messages, "model": model, "max_tokens": 4096}
    if system is not None:
        data["system"] = system
    res = requests.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "Content-Type": "application/json",
            "X-Api-Key": API_KEY,
            "anthropic-version": "2023-06-01",
        },
        json=data,
    )

    if res.status_code == 200:
        return res.json()["content"][0]["text"]

    print(res.status_code)
    print(res.content)

    return res


if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option(
        "-m",
        "--model",
        dest="model",
        default="claude-3-5-sonnet-20240620",
        help="Specify the Claude model to use for chat results",
    )
    parser.add_option(
        "-s",
        "--system",
        dest="system",
        default=None,
        help="Specify a system prompt for this set of messages",
    )
    opts, args = parser.parse_args()

    print(chat(opts.model, [json.loads(msg) for msg in args], system=opts.system))
