#! /usr/bin/python

import sys, os, re, urllib2, BeautifulSoup

def parsePlaylist(listPage):
    "Takes a YouTube playlist page and returns a dict of {u'video name': u'local link', ...}"
    soup = BeautifulSoup.BeautifulSoup(listPage)
    titles = []
    links = []
    for i in soup.ol.findAll('li'):
        titles.append(i.find('span', 'title video-title').string)
        links.append(i.a['href'])
    return dict(zip(titles, links))

def uri2playlist(uri):
    "Takes a video URI and returns that videos' playlist dict (returns false if it's a standalone video)"
    page = urllib2.urlopen(uri).read()
    try:
        playlistURL = re.search("window.location.href=.*?(\/playlist\?list=.*?);", page).group(1)
    except:
        print "No playlist found for '" + uri + "'"
        return False
    playlistPage = urllib2.urlopen("http://www.youtube.com" + playlistURL)
    return parsePlaylist(playlistPage)

def escapeTitle(title): 
    return re.sub(" +", "-", re.sub("[^ \w]", "", title.lower()))

def downloadDict(aDict):
    "Takes a { title: url, ... } dict and downloads each url to the corresponding titled MP4 file"
    for title, url in aDict:
        os.system("get_flash_videos -f \"" + escapeTitle(title)
                  + ".mp4\" http://www.youtube.com" + url)

for uri in sys.argv[1:]:
    uri2playlist(uri)

### test data
# url = "http://www.youtube.com/watch?v=1wSFaGpmVSw&feature=list_related&playnext=1&list=SPFCE355D15056B94D"
# playlistURL = "http://www.youtube.com/playlist?list=PLFCE355D15056B94D&#39"
