#! /usr/bin/python

import sys, os, re
from subprocess import check_output, call

def dict_from_block(block):
    b = block.split("\n")
    return {
        "id": int(b[0]),
        "name": b[1].split(": ", 1)[1],
        "parent": int(b[3].split(": ", 1)[1])
    }

def get_file_list():
    blocks = check_output(["mtp-files"]).split("File ID: ")[1:] # skip some opening diagnostics
    return map(dict_from_block, blocks)

files = get_file_list

def matched_by(term):
    res = []
    for f in files:
        if re.match(term, f["name"]):
            res.append(f)
    return res

for term in sys.argv[1:]:
    for f in matched_by(term):
        call(["mtp-getfile", f["id"], f["name"]])
