#!/usr/bin/python

import sys
from optparse import OptionParser
from subprocess import call

commands = { "tar"     : ["tar", "-cvf"],
             "tar.gz"  : ["tar", "-zcvf"],
             "tgz"     : ["tar", "-zcvf"],
             "tar.bz2" : ["tar", "-jcvf"],
             "zip"     : ["zip", "-r"] }

### parse command line options
parser = OptionParser()
parser.add_option("-t", "--type", dest="type", default="tar",
                  help = "Default: tar --- " + ", ".join(commands.keys()))
(options, args) = parser.parse_args()
##############################

try: cmd = commands[options.type] 
except KeyError as error:
    print "Supported types are: " + ", ".join(commands.keys())
    sys.exit()

for folder in args:
    clean = folder.rstrip("/")
    call(cmd + [clean + "." + options.type, clean])
