#!/usr/bin/python3

import sys, os, re
from optparse import OptionParser


def rename(name):
    if options.regex:
        name = re.sub(options.regex, options.sub, name)
    if options.downcase:
        return name.lower()
    return name


if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option(
        "-r",
        "--regex",
        dest="regex",
        default=False,
        help="Specify the regular expression to replace",
    )
    parser.add_option(
        "-s",
        "--sub",
        dest="sub",
        default="",
        help="Specify what to substitute. By default the empty string (matches are stripped)",
    )
    parser.add_option(
        "-d",
        "--downcase",
        dest="downcase",
        default=False,
        action="store_true",
        help="If passed, specified filenames will be downcased",
    )
    parser.add_option(
        "-D", "--dry-run",
        dest="dry_run", default=False, action="store_true",
        help="If passed, print renamings but don't actually change files on disk."
    )
    (options, args) = parser.parse_args()

    if len(args) <= 0:
        parser.print_help()
        sys.exit()

    if options.dry_run:
        print("DRY RUN...")

    for filename in args:
        new = rename(filename)
        if not options.dry_run:
            os.rename(filename, new)
        if new != filename:
            print(f"  '{filename}' -> '{new}'")
