#!/usr/bin/python
import sys, re
from optparse import OptionParser
from subprocess import call

archiveTypes = { "tar"     : ["tar", "-xvf"],
                 "tar.gz"  : ["tar", "-zxvf"],
                 "tgz"     : ["tar", "-zxvf"],
                 "tar.bz2" : ["tar", "-jxvf"],
                 "rar"     : ["unrar"],
                 "zip"     : ["unzip"],
                 "7z"      : ["7zr", "e"]}

for aFile in sys.argv[1:]:
    fileType = re.search("\.([^\W0-9]{3}?(\.\w+)?)$", aFile).group(1)
    try: cmd = archiveTypes[fileType]
    except KeyError as error:
        print "I have no idea what to do with a '" + fileType + "' file"
    else:
        if fileType=="tar.bz2":
            call(["bunzip2", aFile])
            call(cmd + [re.sub(".bz2$", "", aFile)])
        else:
            call(cmd + [aFile])
