#!/usr/bin/python3
import sys, re
from optparse import OptionParser
from subprocess import call

archiveTypes = {
    "tar": ["tar", "-xvf"],
    "gz": ["gunzip"],
    "tar.gz": ["tar", "-zxvf"],
    "tgz": ["tar", "-zxvf"],
    "tar.bz2": ["tar", "-jxvf"],
    "rar": ["unrar", "x"],
    "cbr": ["unrar", "e"],
    "zip": ["unzip"],
    "7z": ["7zr", "e"],
    "xz": ["xz", "-d", "-v"],
}

for aFile in sys.argv[1:]:
    fileType = re.search(r"\.([^\W0-9]{2,3}?(\.\w+)?)$", aFile).group(1)
    try:
        cmd = archiveTypes[fileType]
    except KeyError:
        print(f"I have no idea what to do with a '{fileType}' file")
    else:
        if fileType == "tar.bz2":
            call(["bunzip2", aFile])
            call(cmd + [re.sub(".bz2$", "", aFile)])
        else:
            call(cmd + [aFile])
