#!/usr/bin/python

import sys, re, urllib
from subprocess import call

inp = raw_input("Webjump: ").split(" ", 1)

def get_url(inp):
    jump = inp[0]
    query = urllib.quote(inp[1])
    jumps = [("youtube", "http://www.youtube.com/results?search_query=" + query + "\&aq=f"),
             ("stockxchange", "http://www.sxc.hu/browse.phtml?f=search\&txt=" + query + "\&w=1\&x=0\&y=0"),
             ("google", "http://www.google.com/search?q=" + query + "\&ie=utf-8\&oe=utf-8\&aq=t"),
             ("wikipedia", "http://en.wikipedia.org/wiki/Special:Search?search=" + query + "\&sourceid=Mozilla-search"),
             ("gmail", "http://mail.google.com")]
    for (k, v) in jumps:
        if re.search(jump, k):
            return v
    return False

url = get_url(inp)
if url:
    call(["lynx", url])
else:
    print "Can't find webjump '"+inp[0]+"'"
    
